apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-k8-c2
  name: service-k8-c2
spec:
  type: ClusterIP
  ports:
  - name: service-port-k8-c2
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-k8-c2